dist: trusty
language: ruby
rvm:
  - 2.4.4
  - 2.5.1
  - ruby-head
env:
  - DRIVER=google-chrome TZ=Europe/Berlin

matrix:
    fast_finish: true
    allow_failures:
      - rvm: ruby-head
before_install:
  - gem install bundler
before_script:
  - bundle install --jobs=3 --retry=3
script: bundle exec rspec
