dist: trusty
language: ruby
cache: bundler
rvm:
  - 2.4.4
  - 2.5.1
  - ruby-head
env:
  - DRIVER=google-chrome TZ=Europe/Berlin
matrix:
    fast_finish: true
    allow_failures:
      - rvm: ruby-head
before_install:
  - gem install bundler
before_script:
  - bundle install --jobs=3 --retry=3
script: bundle exec rspec
deploy:
  provider: rubygems
  gem: hyper-rails
  gemspec: hyper-rails.gemspec
  api_key:
    secure: VEGw8koBHyaWCGtwC4xJgzcY7baR+9JUydj6hm326s1GLNStjWDxxelLqPZC1NQlV8mvoaO+U1d5SQhZJR+Iz6eMP3pz36IpI3FxRwjmThMWGWstT/yJrQNeSVi3lMDU10EieTWckvKz28cOvm/NXJQ7ph6DG1Eo4kPh35YdElI+cInzoGw4oeQMHjU6/evRl/yYmp/6J0tPq+a/ScDWePPh+9NlH+2I+HnkEK89XqK5RvN8MtOG/0y/BtjxFeaj9Ctzkgwbo48w8G6KdEplCTtqrTVVi0gp0A5y3cBYLD+DubcRl+cgebvybw/TsrQKpCrLNzqbQXAFFE+QiTjllG5QCY1FVbu7CT3kV8fWpaxRNz3GATTrqymTa5QIFEsSkawryOHCE2PT0Ys+dke1LJVoIBRt75+f4lopkuf5CHQdALrUk1TceBRXDckgvkgA0cy8zvd4Mm09tMoA0Pmz8WYe8E0nbow+jzMFhnuWUDyCoTG6Hv+bGz5SFM/P3quIgUBIPDXCjcGbbbrO0hbSY6ULi26Oucg1q8o9W/10icF2xDYaLtagl+9/ZsUcdLpKMU8g43QflD1ZHE773H1YwkVP6jlwyDlMYOjRsnj6ktBp93wsYagK+w8bXCfQ6nT01QqhzyLY7YewR2qR7+8wbfRR+/WRO4qf7l6cp/Sqql0=
  on:
    tags: true
    rvm: 2.4.4
